### PR TITLE
shorten description in overview

### PR DESCRIPTION
**Pull request by Laserlicht**
@dydzio0614

### CODE REVIEW

**Comment by Laserlicht** [comment]
@IvanSavenko Ready to merge. Strip out HTML & shorten description in overview

**Comment by IvanSavenko** [comment]
For shortening - perhaps allow some hidden mark in description so modder can specify where short description ends?
Will check if something like this is possible with markdown version of descriptions

**Comment by Olegmods** [comment]
> For shortening - perhaps allow some hidden mark in description so modder can specify where short description ends? Will check if something like this is possible with markdown version of descriptions

 And starts probably.

**Comment by Olegmods** [comment]
Screenshot_2024-11-17-17-29-28-309_com android chrome
So instead of the full version, site will display sth like this:
IMG_20241117_172946

**Pull request merged**
