### PR TITLE
Add discord link + faq icon

### PR DESCRIPTION
**Pull request by dydzio0614**
No titlebar icon for discord BTW

If you think discord shouldn't be added to main page yet then let me know

### CODE REVIEW

**Comment by DjWarmonger** [comment]
Oh, I thought Discord will be added to "Follow us" section, as other social media.

**Comment by IvanSavenko** [comment]
> No titlebar icon for discord BTW

I think website uses Font Awesome which does have discord icon:
https://fontawesome.com/icons/discord?s=solid&f=brands
So it may be possible to add it?

**Comment by dydzio0614** [comment]
Doesn't seem to be trivial for me to update to font awesome 6. Let's merge as is?

**Comment by IvanSavenko** [comment]
If not trivial the yeah, sure. Better than nothing.

**Pull request merged**
